version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists and installing Nginx..."
      - apt-get update
      - apt-get install -y nginx
  build:
    commands:
      - echo "Copying files to the Nginx document root..."
      - mkdir -p /var/www/html
      - cp -R * /var/www/html/
  post_build:
    commands:
      - echo "Starting Nginx to serve the static site..."
      - nginx -g "daemon off;"
      - echo "Nginx is now serving your static site on port 80."
artifacts:
  files:
    - index.html
    - style.css

